server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  data:
      mongodb:
        authentication-database: <AUTH-DB>
        database: <DB-NAME>
        password: ENC(<ENCRYPTED_PASSWORD>)
        uri: mongodb+srv://<USERNAME>:${spring.data.mongodb.password}@<ADDRESS>/${spring.data.mongodb.database}?authSource=<AUTH-DB>&retryWrites=true&w=majority

jasypt:
  encryptor:
    password: <ENCRYPTOR-PASSWORD>

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka